name: License NPM

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

# Cancel old runs when new commit pushed to PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  license-check:
    runs-on: ubuntu-latest
    name: License Check
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run license check
        uses: enthus-appdev/oss-actions/npm-license-validator@v1
        with:
          forbidden_licenses: ${{ vars.FORBIDDEN_LICENSES }}
