name: License Node

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  license-check:
    runs-on: ubuntu-latest
    name: License Check
    if: github.event_name != 'pull_request' || (!github.event.pull_request.draft && !contains(github.event.pull_request.title, 'WIP'))
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run license check
        uses: enthus-appdev/actions/node-license-validator@main
        with:
          forbidden_licenses: ${{ vars.FORBIDDEN_LICENSES }}
